landscapeMemberClasses:
  - name: Premier 100k
    category: Premier
  - name: Premier 250k
    category: Premier
  - name: Strategic Membership
    category: Strategic
  - name: Start-up Strategic Membership
    category: Strategic
  - name: Community Membership
    category: Community
slug: risc-v-international
landscapeMemberCategory: RISC-V Members
