global:
  name: RISC-V Ecosystem Interactive Landscape
  short_name: RISC-V
  repo: riscv-admin/riscv-landscape
  website: https://landscape.riscv.org
  short_domain: l.riscv.org
  company_url: https://riscv.org/
  email: info@riscv.org
  self: https://www.crunchbase.com/organization/riscv
  hide_no_best_practices: true
  meta:
    title: RISC-V Interactive Landscape
    description: RISC-V Landscape Info
    twitter: '@risc_v'
    google_site_verification: test
    ms_validate: test
    extra: >
      <meta property="og:image" content="https://landscape.riscv.org/images/social.png" /> <meta property="og:image:width" content="1800" /> <meta
      property="og:image:height" content="945" /> <meta property="og:locale" content="en_US" /> <meta property="og:type" content="website" /> <meta
      property="og:title" content="Landscape" /> <meta property="og:description" content="The Landscape organizes all RISC-V native open source projects and
      proprietary products into categories, providing an overview of the current ecosystem" /> <meta property="og:url" content="https://landscape.riscv.org/" />
      <meta property="og:site_name" content="Landscape" /> <meta name="twitter:card" content="summary_large_image" /> <meta name="twitter:title"
      content="Landscape" /> <meta name="twitter:description" content="The Landscape organizes all RISC-V open source projects and proprietary products into
      categories, providing an overview of the current ecosystem" /> <meta name="twitter:image" content="https://landscape.riscv.org/images/social.jpg" /> <meta
      name="twitter:image:width" content="1800" /> <meta name="twitter:image:height" content="945" /> <script>
        window.addEventListener("DOMContentLoaded", function() {
          const element = document.querySelector('.disclaimer');
          element.innerHTML = element.innerHTML.replace('Greyed logos are not open source.', '');
        });
      </script> <script>
        window.addEventListener("DOMContentLoaded", function() {
          document.querySelector('.select[data-name=project]').style.display = "none";          
        });
      </script> <script>
        window.addEventListener("DOMContentLoaded", function() {
          document.querySelector('.select[data-name=headquarters]').style.display = "none";          
        });
      </script>
  membership: RISC-V Members
twitter:
  search: riscv.cncf.io
  url: https://landscape.riscv.org
  text: RISC-V Landscape from @risc_v
relation:
  label: RISC-V Relation
  url: riscv
  values:
    - id: hosted
      label: RISC-V Projects
      children:
        - id: projects
          label: Riscv Projects
          prefix: Riscv
          tag: Projects
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Riscv Projects
          big_picture_color: rgb(24,54,114)
    - id: member
      label: RISC-V Member Products/Projects
      tag: Riscv Member
    - id: false
      label: Non-RISC-V Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: RISC-V
    label: Premier Member
    funding: Premier
    is_large: true
  Strategic:
    name: RISC-V
    label: Strategic Member
    funding: Strategic
    is_large: true
  Community:
    name: RISC-V
    label: Community Member
    funding: Community
home:
  header: >
    <h1>RISC-V Ecosystem Interactive Landscape</h1> The RISC-V landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://riscv-europe.org/summit/2024/
    image: /images/SummitEurope2023v2.png
    title: RISC-V Summit Europe 2024
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Cards by age
  - url: /license=open-source
    label: Open source landscape
  - url: /category=cncf-members&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters&headquarters=china,hong-kong,taiwan
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    short_name: Land...
    title: RISC-V Landscape
    elements:
      - type: HorizontalCategory
        is_large: true
        category: Applications
        rows: 2
        width: 1350
        height: 175
        top: 0
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Libraries
        rows: 2
        width: 1350
        height: 175
        top: 185
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Infrastructure
        rows: 1
        width: 670
        height: 100
        top: 370
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Runtimes
        rows: 1
        width: 670
        height: 100
        top: 370
        left: 680
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Operating Systems
        rows: 2
        width: 1350
        height: 175
        top: 480
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Hypervisor
        rows: 1
        width: 670
        height: 100
        top: 665
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Boot
        rows: 1
        width: 670
        height: 100
        top: 665
        left: 680
        color: rgb(109,61,143)
      - type: LandscapeInfo
        width: 1350
        height: 100
        top: 1490
        left: 0
        children:
          - type: text
            text: >-
              This landscape is intended to provide insight into the rich RISC-V Ecosystem available today. Further details on RISC-V Software Ecosystem Status
              available at https://sites.google.com/riscv.org/software-ecosystem-status.
            top: 49
            left: 20
            right: 20
            font_size: 12
          - type: image
            image: right-logo.svg
            width: 109
            right: 15
            top: 15
            title: RiscV Logo
          - type: image
            image: left-logo.svg
            width: 140
            left: 15
            top: 15
            title: Landscape Logo
    fullscreen_header: https://riscv.org/
  members:
    tab_index: 2
    name: RISC-V Members
    url: members
    short_name: Memb....
    title: RISC-V Members
    fullscreen_header: https://riscv.org/members/
    category: RISC-V Members
    elements:
      - type: HorizontalCategory
        is_large: true
        category: Premier
        rows: 2
        width: 1100
        height: 175
        top: 0
        left: 0
        color: rgb(109,61,143)
      - type: HorizontalCategory
        is_large: true
        category: Strategic
        rows: 12
        color: rgb(109,61,143)
        left: 0
        width: 1350
        height: 750
        top: 185
      - type: HorizontalCategory
        is_large: true
        category: Community
        rows: 2
        width: 240
        height: 175
        top: 0
        left: 1110
        color: rgb(109,61,143)
test:
  header: RISC-V Ecosystem Interactive Landscape
  section: Non-RISC-V Member Products/Projects
  logo: my-sql.svg
prerender: {}
export: {}
